version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sonjanggo
      MYSQL_USER: sonjanggo
      MYSQL_PASSWORD: 0919
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/sonjanggo
      SPRING_DATASOURCE_USERNAME: sonjanggo
      SPRING_DATASOURCE_PASSWORD: 0919
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
